const ListofProducts = [
    {
        id : 1,
        name : 'Iphone 13 ',
        description : 'Mini 128gb',
        prize : 300000,
        img : './assets/products/iphone-13-mini-128-gb-2.png',
        category : 'iphone',
    } ,
    {
        id : 2,
        name : 'iPad Air 64gb',
        description : '10,2" Wi-Fi 2021',
        prize : 122000,
        img : './assets/products/ipad-air-select-wifi-gold-202009.png',
        category : 'ipad',
    } ,
    {
        id : 3,
        name : 'MacBook Air 13"',
        description : '8-Core CPU 512 GB',
        prize : 372000,
        img : './assets/products/macbook-air-13-m1-2020-8-core-cpu-256-gb-space-gray.png',
        category : 'macbook',
    } ,
    {
        id : 4,
        name : 'iPhone SE',
        description : '(3rd Generacion) - 64 GB',
        prize : 140000,
        img : './assets/products/iphone se.jpg',
        category : 'iphone',
    } ,
    {
        id : 5,
        name : 'iPhone 12',
        description : '128 GB',
        prize : 350300,
        img : './assets/products/iphone-12-128-gb-300x300.jpg',
        category : 'iphone',
    } ,
    {
        id : 6,
        name : 'iPhone 14 Pro',
        description : '128 GB',
        prize : 494000,
        img : './assets/products/iphone-14-pro-128-gb-300x300.jpg',
        category : 'iphone',
    } ,
    {
        id : 7,
        name : 'iPhone 14 Pro Max',
        description : '256 GB',
        prize : 568000,
        img : './assets/products/iphone-14-pro-128-gb-300x300.jpg',
        category : 'iphone',
    } ,
    {
        id : 8,
        name : 'iPad Air',
        description : '10,9" Wi-Fi 4 GB',
        prize : 120000,
        img : './assets/products/ipad air.jpg',
        category : 'ipad',
    } ,
    {
        id : 9,
        name : 'MacBook Pro 16"',
        description : '16 coreCPu 512GB SSD',
        prize : 432000,
        img : './assets/products/macbook-pro-16-apple-m1-pro-chip-10core-cpu-16core-gpu-512gb-ssd-space-grey-300x300.jpg',
        category : 'macbook',
    } ,
    {
        id : 10,
        name : 'MacBook Pro M1',
        description : '256000',
        prize : 410000,
        img : './assets/products/mbp-spacegray-gallery2-202011_GEO_US-scaled-1-300x300.jpeg',
        category : 'macbook',
    } ,
    {
        id : 11,
        name : 'AppleWatch Series 7 GPS',
        description : '41mm Blanco Estrella',
        prize : 121999,
        img : './assets/products/watch s7 gps.jpg',
        category : 'watch',
    } ,
    {
        id : 12,
        name : 'Applewatch Series 3 GPS',
        description : '42mm Space Gray',
        prize : 68000,
        img : './assets/products/a-watch-s-3-gps-42mm-sga-case-300x300.jpg',
        category : 'watch',
    } ,
    {
        id : 13,
        name : 'Apple Watch SE GPS (2020)',
        description : '44mm Space Gray',
        prize : 90000,
        img : './assets/products/watch se.jpg',
        category : 'watch',
    } ,
    {
        id : 14,
        name : 'Cargador Apple Origianl',
        description : 'Usb-c 20w',
        prize : 9000,
        img : './assets/products/cargador.jpg',
        category : 'accesorios',
    } ,
    {
        id : 15,
        name : 'Airpod 2',
        description : 'Estuche carga inalámbrica',
        prize : 39000,
        img : './assets/products/airpod.jpg',
        category : 'accesorios',
    } ,
    {
        id : 16,
        name : 'Funda silicona',
        description : 'MagSafe (varios colores)',
        prize : 13000,
        img : './assets/products/funda.jpg',
        category : 'accesorios',
    } ,
    {
        id : 17,
        name : 'Cable Cargador',
        description : 'Mag (1m)',
        prize : 10000,
        img : './assets/products/cable.jpg',
        category : 'accesorios',
    } ,

];